import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link"; // Import Link from Next.js

// const geistSans = localFont({
// 	src: "./fonts/GeistVF.woff",
// 	variable: "--font-geist-sans",
// 	weight: "100 900",
// });
// const geistMono = localFont({
// 	src: "./fonts/GeistMonoVF.woff",
// 	variable: "--font-geist-mono",
// 	weight: "100 900",
// });

export const metadata: Metadata = {
	title: "AiTools",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* Add navigation bar */}
				<nav className="flex justify-center space-x-6 py-4 bg-black/[.05] dark:bg-white/[.06] ">
					<Link href="/" className="text-lg font-bold hover:text-blue-500">
						Home
					</Link>
					<Link
						href="/settings"
						className="text-lg font-bold hover:text-blue-500"
					>
						Settings
					</Link>
				</nav>
				{/* Add a container with a maximum width */}
				<div className="max-w-4xl mx-auto p-4">
					{children}
				</div>
			</body>
		</html>
	);
}
